name: Cron-Job-For-Allocate-Parking
on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: daily-allocate-parking
        run: |
          curl --request POST \
          --url 'https://office-space-sync.vercel.app/api/allocate-parking' \
          --header 'authorization: ${{ secrets.AUTHORIZATION }}'
