name: Cron-Job-For-Clear-Bookings
on:
  workflow_dispatch:
  schedule:
    - cron: "15 12 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: daily-clear-bookings
        run: |
          curl --request DELETE \
          --url 'https://office-space-sync.vercel.app/api/clear-bookings' \
          --header 'Authorization: ${{ secrets.AUTHORIZATION }}'
